canvas:
  background: '#EEF3FB'
  grid: ''
  padding: 60
theme:
  presets:
    s:
      palette:
        topGradient:
          from: '#DCE9FF'
          to: '#BFD6FA'
          dir: down
        leftGradient:
          from: '#9FC0F2'
          to: '#7FA8EC'
          dir: down
        rightGradient:
          from: '#B4CFF6'
          to: '#93B8F0'
          dir: down
      effects:
        cornerRadius: 8
        opacity: 0.6
        backglow:
          color: '#9CC2FF'
          radius: 46
          opacity: 0.35
nodes:
  scene:
    shape: composite
    layout:
      mode: row
      gap: 1.2
    parts:
    - id: a
      shape: rectangle
      preset: s
      geom:
        w: 90
        d: 90
        h: 34
      label: frosted-glass
    - id: b
      shape: rectangle
      preset: s
      geom:
        w: 80
        d: 80
        h: 80
    - id: c
      shape: cylinder
      preset: s
      geom:
        w: 80
        d: 80
        h: 44
